#!/bin/bash
## Get system info
user="${USER}@$(hostname)"
distro='Debian 10.0'
kernel="$(uname -sr | sed 's/-.*//')"
uptime="$(uptime -p | sed 's/up //')"
packages="$(dpkg -l | wc -l)"
shell="$(basename ${SHELL})"

if [ -z "${WM}" ]; then
		envtype='WM'
		WM="Openbox"
fi

## Define Colours
if [[ $1 = "--red" ]]; then
    bgaccent="$(tput setab 1)"
    accent="$(tput setaf 1)"
elif [[ $1 = "--green" ]]; then
    bgaccent="$(tput setab 2)"
    accent="$(tput setaf 2)"
elif [[ $1 = "--yellow" ]]; then
    bgaccent="$(tput setab 3)"
    accent="$(tput setaf 3)"
elif [[ $1 = "--blue" ]]; then
    bgaccent="$(tput setab 4)"
    accent="$(tput setaf 4)"
elif [[ $1 = "--magenta" ]]; then
    bgaccent="$(tput setab 5)"
    accent="$(tput setaf 5)"
elif [[ $1 = "--cyan" ]]; then
    bgaccent="$(tput setab 6)"
    accent="$(tput setaf 6)"
else
    bgaccent="$(tput setab 1)"
    accent="$(tput setaf 1)"
fi

bold="$(tput bold)"
white="$(tput setaf 7)"
yellow="$(tput setaf 3)"
red="$(tput setaf 1)"
blue="$(tput setaf 4)"
green="$(tput setaf 2)"
orange="$(tput setaf 8)"
violet="$(tput setaf 5)"
cyan="$(tput setaf 6)"
reset="$(tput sgr0)"
cbg="${reset}${bold}${bgaccent}${white}"
cr="${reset}"
c0="${reset}${bold}"
c1="${reset}${accent}"

## Output

cat <<EOF

  ${c0}${cbg}    _____    ${c0}${white}    USER${reset}       ${c0}${violet}${user}${reset}
  ${c0}${cbg}   /  __ \\   ${c0}${white}    DISTRO     ${c0}${red}${distro}${reset}
  ${c0}${cbg}  |  /    |  ${c0}${white}    KERNEL     ${c0}${yellow}${kernel}${reset}
  ${c0}${cbg}  |  \\___-   ${c0}${white}    UPTIME     ${c0}${cyan}${uptime}${reset}
  ${c0}${cbg}  -_         ${c0}${white}    ${envtype}         ${c0}${orange}${WM}${reset}
  ${c0}${cbg}    --_      ${c0}${white}    SHELL      ${c0}${green}${shell}${reset}
  ${c0}${cbg}             ${c0}${white}    PACKAGES   ${c0}${blue}${packages}${reset}
EOF

f=3 b=4
for j in f b; do
  for i in {0..7}; do
    printf -v $j$i %b "\e[${!j}${i}m"
  done
done
d=$'\e[1m'
t=$'\e[0m'
v=$'\e[7m'
 
 
pcs() { for i in {0..7}; do echo -en "\e[${1}$((30+$i))m\u2580 \e[0m"; done; }
printf "\n\t\t  %s\n" "$(pcs)"
